spring.application.name=TripProject

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.datasource.url=jdbc:mysql://localhost:3306/ssafytrip?serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=ssafy
spring.datasource.password=ssafy

spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=600000
spring.datasource.hikari.idle-timeout=300000


mybatis.type-aliases-package=com.*.**.dto
mybatis.mapper-locations=classpath:/mappers/**/*.xml

## accessToken 1시간 refreshToken 1주일
ssafy.jwt.access-expmin=60
ssafy.jwt.refresh-expmin=10080
ssafy.jwt.secret=s3cr3tJwT_k3y_2025_ssafy_P!9xT7vBqLz0FgYdKmNsW2eH

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kimjy9307@gmail.com
spring.mail.password=redzzdgrjkpfgfvk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.maxCompletionTokens=10000

ssafy.ai.system-prompt=You are an employee at a company that manages the AI SSAFY travel website.